<h1>
	Das Haus
</h1>
<p>Das Tagungshaus in der Nähe von Großgoltern (bei Hannover) eignet sich für Seminare mit bis zu 100 Menschen.</p>

<h4>
	Drinnen
</h4>
<p>Der Gebäudekomplex umfasst viele Tagungs- und Entspannungsräume, sowie diverse querbeet verteilte Schlaf- und Badezimmer für drei bis zehn Personen. Außerdem gibt es eine Großküche, in der sich problemlos Essen für sehr viele Menschen zaubern lässt.</p>
<p>Leider ist die WLAN-Ausstattung in dem Haus eher mangelhaft - insbesondere, was den Empfang angeht. Wer also zuhause noch einen Router rumliegen hat, den er für die paar Tage entbehren kann, kann den gerne mitbringen.</p>

<h4>
	Draußen
</h4>
<p>Das Außengelände ist sehr weitläufig, da das Tagungshaus auf dem Land liegt. Es gibt zwei von Baumringen umgebene große Wiesen, die, wenn wir denn so viele werden sollten, auch als Campingplätze umfunktioniert werden können. Neben der wohl nicht zur Anwendung kommenden Außendusche finden sich hier</p>
<ul>
	<li>eine übderdachte Terrasse, auf der bei bewonders gutem Wetter luftig leichte Workshops stattfinden können, oder auch gegessen wird,</li>
	<li>einen ausreichend bestuhlten Hof,</li>
	<li>eine Feuerstelle,</li>
	<li>ein Pavillon, damit man auch noch bei Sturm und Gewitter nach draußen zum Rauchen gehen kann, sowie</li>
	<li>eine Tischtennisplatte mitsamt (mittelmäßig brauchbarem) Equipment.</li>
</ul>

<h4>
	Unterhaltung
</h4>
<p>Neben der Tischtennisplatte sind mehrere Kicker, sowie ein Billardtisch, vorhanden.</p>

<h4>Schlafplätze</h4>
<p>Im Haus gibt es Betten, für die aber Laken und Bezug mitgebracht werden müssen (können sonst gegen ein paar euro dort auch ausgeliehen werden). Je nach Teilnehmerzahl und Haussituation wäre es dennoch nicht schlecht, wenn ihr Schlafsäcke o.ä. mitbringt - nur für den Fall ;)</p>
