<h1>
	Kosten
</h1>
<p>An reinen Unkosten kostet die Fahrt pro Person etwas über 120 €. Einen Anteil davon haben wir über Stiftungen decken können, einen großen Teil aber leider nicht. Im Schnitt brauchen wir nach aktuellem Stand von allen Teilnehmern noch ca. 60-70 €. Uns ist klar, dass niemand Geld übrig hat und es einige unter euch gibt, für die solche Beträge schon ans Eingemachte gehen. Daher gilt: Schaut, wie viel ihr aufbringen könnt und gebt den Betrag bei der Anmeldung an - wenn ihr absolut pleite seid und auch von euren Eltern nichts für solche Zwecke bekommt, tragt ihr eben das ein und wenn ihr euch auch die Fahrtkosten nicht leisten könnt, gebt das unter "sonstige Infos" an.<br />
<strong>Die finanzielle Lage soll kein Grund sein, nicht zu kommen!</strong></p>