<h1>
	Kosten
</h1>
<p>Der von uns vorgeschlagene Beitrag von 60-70€ sind nicht kostendeckend, d.h. wenn jeder diesen Beitrag zahlt bleiben wir auf einem Teil der Kosten für das Camp sitzen. Daher bitten wir euch, mehr zu bezahlen, falls ihr es euch leisten könnt. Falls ihr nicht mal das notwendige Geld für die 60-70€ aufbringen könnt, soll dass aber kein Grund sein nicht zu kommen - teilt uns das einfach bei der Anmeldung unter "sonstige Infos" mit oder schreibt uns eine Mail, wir finden eine Lösung.<br />
<strong>Die finanzielle Lage soll kein Grund sein, nicht zu kommen!</strong></p>
