<h1>
	Programm
</h1>

<p>Das Haus ist geöffnet von <b>02.06.</b> bis <b>06.06.17</b></p>
<ol>
	<li>Workshopschiene: von <b>03.06., 11 Uhr</b> bis <b>04.06., 14 Uhr</b></li>
	<li>Workshopschiene: von <b>04.06., 17 Uhr</b> bis <b>05.06., 20 Uhr</b></li>
</ol>

<p>Jedes der Themen wird neunstündig (drei mal drei Stunden) behandelt - zwei Themen werden Samstag und Sonntagvormittag behandelt, die beiden anderen Sonntagnachmittag und Pfingstmontag.</p>
<p> </p>
<p><strong>03.-04. Juni</strong> </p>
<table width="100%">
	<tbody>
		<tr>
			<td style="border: 1px dashed #333; padding: 20px;" width="50%">
				<h4>Demokratische Wahlen</h4>
				<p>Samstag von 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr,<br />
					und Sonntag von 11:00 Uhr bis 14:00 Uhr.</p>
				<a href="?workshop=wahl">➙ zum Ankündiger</a>
			</td>
			<td style="border: 1px dashed #333; padding: 20px;">
				<h4>Rechte kritisieren</h4>
				<p>Samstag von 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr,<br />
					und Sonntag von 11:00 Uhr bis 14:00 Uhr.</p>
				<a href="?workshop=rechteKritisieren">➙ zum Ankündiger</a>
			</td>
		</tr>
	</tbody>
</table>
<p> </p>
<p><strong>04.-05. Juni</strong> </p>
<table width="100%">
	<tbody>
		<tr>
			<td style="border: 1px dashed #333; padding: 20px;" width="50%">
				<h4>Flüchtlingspolitik (?)</h4>
				<p>Sonntag von 17:00 Uhr bis 20:00 Uhr,<br />
					und Pfingstmontag 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr.</p>
				<a href="?workshop=fluechtlingspolitik">➙ zum Ankündiger</a>
			</td>
			<td style="border: 1px dashed #333; padding: 20px;">
				<h4>Armut</h4>
				<p>Sonntag von 17:00 Uhr bis 20:00 Uhr,<br />
					und Pfingstmontag 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr.</p>
				<a href="?workshop=armut">➙ zum Ankündiger</a>
			</td>
		</tr>
	</tbody>
</table>
<!--
<h4>Wie man Rassisten kritisiert und wie besser nicht</h4>
<p style="font-family: Tahoma, Helvetica, Arial, sans-serif; font-weight: normal;">Samstag von 11:00 Uhr bis 14:00 Uhr<br />sowie von 17:00 Uhr bis 20:00 Uhr,<br />und Sonntag von 11:00 Uhr bis 14:00 Uhr.<br /><a href="index.php/rassismus">&gt; Hier zum Ankündiger</a></p>
<h4>Wahrheit - gibt es nicht!?</h4>
<p>Samstag von 11:00 Uhr bis 14:00 Uhr,<br />sowie von 17:00 Uhr bis 20:00 Uhr<br />und Sonntag von 11:00 Uhr bis 14:00 Uhr.<br /><a href="index.php/wahrheit">&gt;Hier zum Ankündiger</a></p>
<p> </p>
<h4>Psychologie im Alltag - in der Schule wie im Leben danach</h4>
<p>Sonntag von 17:00 Uhr bis 20:00 Uhr<br />und Montag von 11:00 Uhr bis 14:00 Uhr,<br />sowie von 17:00 Uhr bis 20:00 Uhr.<br /><a href="index.php/psychologie">&gt; Hier zum Ankündiger</a></p>
<h4>Demokratische Wahlen</h4>
<p>Sonntag von 17:00 Uhr bis 20:00 Uhr,<br />und Montag von 11:00 Uhr bis 14:00 Uhr<br />sowie von 17:00 Uhr bis 20:00 Uhr.<br /><a href="index.php/demokratische-wahlen">&gt; Hier zum Ankündiger</a></p>-->
