<h1>
	Programm
</h1>

<p>Das Haus ist geöffnet von <b>02.06.</b> bis <b>06.06.17</b></p>
<ol>
	<li>Workshopschiene: von <b>03.06., 11 Uhr</b> bis <b>04.06., 14 Uhr</b></li>
	<li>Workshopschiene: von <b>04.06., 17 Uhr</b> bis <b>05.06., 20 Uhr</b></li>
</ol>

<p>Jedes der Themen wird neunstündig (drei mal drei Stunden) behandelt - zwei Themen werden Samstag und Sonntagvormittag behandelt, die beiden anderen Sonntagnachmittag und Pfingstmontag.</p>
<p> </p>
<p><strong>03.-04. Juni</strong> </p>
<table>
	<tbody>
		<tr>
			<td>
				<h4>Demokratische Wahlen</h4>
				<p>Samstag von 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr,<br />
					und Sonntag von 11:00 Uhr bis 14:00 Uhr.</p>
				<a onclick="loadWorkshop('wahl')">➙ zum Ankündiger</a>
			</td>
			<td>
				<h4>Rechte kritisieren</h4>
				<p>Samstag von 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr,<br />
					und Sonntag von 11:00 Uhr bis 14:00 Uhr.</p>
				<a onclick="loadWorkshop('rechteKritisieren')">➙ zum Ankündiger</a>
			</td>
		</tr>
	</tbody>
</table>
<p> </p>
<p><strong>04.-05. Juni</strong> </p>
<table>
	<tbody>
		<tr>
			<td>
				<h4>Flüchtlingspolitik (?)</h4>
				<p>Sonntag von 17:00 Uhr bis 20:00 Uhr,<br />
					und Pfingstmontag 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr.</p>
				<a onclick="loadWorkshop('fluechtlingspolitik')">➙ zum Ankündiger</a>
			</td>
			<td>
				<h4>Armut</h4>
				<p>Sonntag von 17:00 Uhr bis 20:00 Uhr,<br />
					und Pfingstmontag 11:00 Uhr bis 14:00 Uhr<br />
					sowie von 17:00 Uhr bis 20:00 Uhr.</p>
				<a onclick="loadWorkshop('armut')">➙ zum Ankündiger</a>
			</td>
		</tr>
	</tbody>
</table>
