<h1>
	Workshop: Superwahljahr - Volksherrschaft in Hochform
</h1>
<p>Das Jahr 2017 wird als „Superwahljahr“ angekündigt. Drei Landtagswahlen und die Bundestagswahl! Für die politischen Parteien sind das wichtige Ereignisse. Mit Kandidaten, Parteitagen und -programmen bemühen sie sich, Profil zu gewinnen und dem Wähler genau die Themen nahe zu bringen, die sie mit ihrer Partei „besetzen“ möchten. Dafür scheuen Politiker keine Mühe. Für sie geht es bei der Wahl ja um einiges; nämlich darum, mit möglichst vielen Stimmen an die Macht zu kommen.</p>

<p>Das umworbene Wahlvolk hat die Wahlen nicht bestellt, sie werden von Oben angesetzt und nach festen Regeln durchgeführt; und das auch dann, wenn ein großer Teil der Wähler nach allgemeiner Einschätzung „wahlmüde“ ist. Die Parteien haben dann die Aufgabe, sie (für sich) zu mobilisieren. Das – so hört man - umso mehr, wenn große Teile des Wahlvolks „politikverdrossen“ sind und – bloß weil sie wählen dürfen! - dazu neigen, ihre Stimme den Falschen (der AfD!) zu geben. Dann müssen die etablierten Parteien alles geben, damit sie die Wahl gewinnen und die Stimmen dieser Protestwähler garantiert bloß „verschenkt“ sind!</p>

<p>Insgesamt liegt bei Wahlen ganz offenbar der aktive Part ganz auf Seiten der „passiv“ Gewählten. Wie das? Ist denn das Volk in der Demokratie nicht der eigentliche Souverän, der durch Wahlen seine Macht betätigt? Dass freie Wahlen stattfinden, ist das nicht das Markenzeichen demokratischer Staatswesen? Hier wird das Volk nicht einfach von der Staatsgewalt unterdrückt, hier bestimmt es selbst, wer die Staatsgewalt ausübt! Worin besteht sie denn nun, diese vielgelobte „Volkssouveränität“?</p> 

<p>Ein Wähler mag sich von seiner Stimmabgabe versprechen, was er will: Dass er einen Maßnahmenkatalog vorgibt, der künftig im Land umgesetzt wird, glaubt wohl keiner. Mit einem wenig mitteilsamen Wahlkreuz lassen sich ja auch gar keine Aufträge an die Politik formulieren und wer solche auf dem Wahlzettel vermerkt, macht ihn im übrigen ungültig.</p> 
<p>Mit seinem Kreuz sagt der Wähler nur soviel: Wen unter den angebotenen Herrschaftsalternativen er am liebsten hätte. Und dann? Dann kriegt der Wähler eine (neue) Regierung. Die, nicht der Wähler, sagt in den nächsten Jahren, wo es lang geht im Land. Und diese Regierung ist in jedem Fall auch „seine“, egal wer die Wahl gewinnt: Der Wähler hat mit der Wahl unterschrieben, dass jede Regierung als seine Regierung legitimiert ist, die die Mehrheit der gleichgeltenden Stimmen auf sich vereinigen kann.</p> 
<p>Auf die Wählerstimmen kommt's in der Demokratie insofern mächtig an: Daraus wird eine neue Herrschaft gebildet. Die kann sich in ihrer souveränen Ausübung der Regierungsgewalt auf den Wähler berufen. Wenn der dann über ihre Politik und die Ergebnisse für ihn unzufrieden ist, kann er bei der nächsten Wahl ja die Opposition wählen, die verspricht ihm eine (personelle) Alternative…</p>
<p></p>
<p>Im Workshop soll dieses merkwürdige demokratische Verhältnis zwischen Oben und Unten diskutiert und bestimmt werden. Das wird mit Sicherheit kein gutes Licht auf die Demokratie werfen.</p>
