<h1>
	Workshop: Wie man die Ausländerfeindlichkeit von AfD und Pegida kritisiert und wie nicht!
</h1>
Dass die Flüchtlinge uns die Arbeitsplätze wegnehmen, das leuchtet auch so manchem von denen ein, die sich zu den Gegnern von AfD und Pegida rechnen und sich von Nationalismus und Rassismus distanzieren. Die Rechnung scheint ja auch sehr einfach zu sein: Je mehr Menschen auf dem Arbeitsmarkt um knappe Arbeitsplätze konkurrieren, desto schwerer wird es für jeden einzelnen Bewerber, sein Ziel zu erreichen. Aber geht es der ausländerfeindlichen Parole der AfD überhaupt darum, Leuten in ihren Konkurrenznöten zu helfen, wie immer die sie deuten? Die AfD will ja begründen, dass Ausländer, Flüchtlinge zumal, bei uns nichts verloren haben. Folglich wirft sie ganz andere Fragen auf:
– Was behauptet die AfD damit über die Konkurrenz?
– Welches Urteil fällt sie über Arbeitsplätze und den Arbeitsmarkt?
– Worüber wird in der Konkurrenz denn tatsächlich entschieden?
– Was behauptet das Urteil, dass Arbeitsplätze allein ein Besitzstand der Inländer sind?
– Was soll die Gesamtheit der Inländer, das „uns“, eigentlich ausmachen?
– Warum soll mit dem Verweis auf „unseren Arbeitsmarkt“ bereits über die Ausgrenzung von
Ausländern entschieden sein?
– Und was wird der Flüchtlingspolitik der Kanzlerin damit alles vorgeworfen?
Diese und weitere Fragen zur Sache sollen auf dem Workshop in drei Sitzungen an einschlägigem Material erörtert werden.