<header id="header">
	<h1>Argumente gegen das Zeitgeschehen</h1>
	<nav>
		<ul>
			<li onClick="loadPage('allgemeines')" id="lastSelected"><b>Allgemeines</b></li>
			<li onClick="loadPage('programm')"><b>Programm</b></li>
			<li onClick="loadPage('haus')"><b>Das Haus</b></li>
			<li onClick="loadPage('kosten')"><b>Kosten</b></li>
			<li onClick="loadPage('anfahrt')"><b>Anfahrt</b></li>
			<li onClick="loadPage('anmeldung')"><b>Anmeldung</b></li>
			<li onClick="loadPage('kontakt')"><b>Kontakt</b></li>
		</ul>
	</nav>
</header>
