<header id="header">
	<h1>Argumente gegen das Zeitgeschehen</h1>
	<nav>
		<ul>
			<li><a href="?p=allgemeines">Allgemeines</a></li>
			<li><a href="?p=programm">Programm</a></li>
			<li><a href="?p=haus">Das Haus</a></li>
			<li><a href="?p=kosten">Kosten</a></li>
			<li><a href="?p=anfahrt">Anfahrt</a></li>
			<li><a href="?p=anmeldung">Anmeldung</a></li>
			<li><a href="?p=kontakt">Kontakt</a></li>
		</ul>
	</nav>
</header>
