<aside id="sidebar">
	<section id="unter18">
		<h1>Für alle unter 18</h1>
		<p>Um das ganze auch rechtlich etwas sicherer zu machen, haben wir auch einen Muttibrief geschrieben, den nach Möglichkeit alle Minderjährigen unterschieben mitbringen sollen. Wenn es dabei Probleme gibt, schreibt uns einfach an.</p>
	</section>

	<section id="daten">
		<h1>Daten</h1>
		<p>Das Haus ist geöffnet vom <b>02.06.</b> bis <b>06.06.17</b></p>
		<ol>
			<li>Workshopschiene: von <b>03.06., 11 Uhr</b> bis <b>04.06., 14 Uhr</b></li>
			<li>Workshopschiene: von <b>04.06., 17 Uhr</b> bis <b>05.06., 20 Uhr</b>
		</ol>
	</section>

	<section id="kontakt">
		<h1>Kontakt</h1>
		<p>Wenn es noch Fragen gibt, die nicht auf dieser Website beantwortet werden, könnt ihr uns auch unter <a mailto="seminarwochenende@riseup.net">seminarwochenende@riseup.net</a> erreichen.<br />
		Außerdem könnt ihr euch <a href="https://lists.riseup.net/www/subscribe/zeitgeschehen">hier</a> in den Verteiler eintragen.</p>
	</section>	
</aside>
